### ISSUE TITLE
您好，想问一个关于CenterNet损失的问题。

### ISSUE THREAD

**Issue by Hello-Felix** [zzzxxxttt/pytorch_simple_cornernet#1]
前辈您好，我最近做一个钢筋检测（密集小目标）任务，网络使用Unet++，想先试试直接回归中心点的效果，我直接输出了一层feature map，揭取了官方heatmap（C*H*W）部分的损失代码片段：def _neg_loss(preds, targets):。我发现因为没有对损失做平均（除以W*H），跑起来发现损失值很大，也不下降。在除以W*H后，损失值小了，但是训练后没学到东西，输出的feature map全是0。

我想问前辈两个问题：
（1）在你的代码里网络Heatmap分支的输出结果在损失前并没有套Sigmoid，为什么。
（2）为什么CenterNet的损失没有做平均，而仅仅用N做了一个Normalize。

**Comment by zzzxxxttt** [comment]
> 前辈您好，我最近做一个钢筋检测（密集小目标）任务，网络使用Unet++，想先试试直接回归中心点的效果，我直接输出了一层feature map，揭取了官方heatmap（C_H_W）部分的损失代码片段：def _neg_loss(preds, targets):。我发现因为没有对损失做平均（除以W_H），跑起来发现损失值很大，也不下降。在除以W_H后，损失值小了，但是训练后没学到东西，输出的feature map全是0。
> 
> 我想问前辈两个问题：
> （1）在你的代码里网络Heatmap分支的输出结果在损失前并没有套Sigmoid，为什么。
> （2）为什么CenterNet的损失没有做平均，而仅仅用N做了一个Normalize。

1) heatmap的输出经过了sigmoid，在losses.py第16行
2) 因为是对每个物体单独预测特征点，所以要除以物体的数量，如果不按物体数量归一化就容易过拟合到包含物体多的图片。

**Comment by Hello-Felix** [comment]
非常感谢！
