### ISSUE TITLE
Error in annotation of CoCo?

### ISSUE THREAD

**Issue by SohamTamba** [zzzxxxttt/pytorch_simple_cornernet#4]
In th CoCo dataset, the annotations in this line `    bboxes[:, 2:] += bboxes[:, :2]  # xywh to xyxy` might be wrong.
According to that line.

```
x_right = x_left + width
y_bottom = y_top + height 
```
Shouldn't it be
`y_bottom = y_top - height`?

Link: https://github.com/zzzxxxttt/pytorch_simple_CornerNet/blob/767bf0af3229d9ffc1679aebdbf5eb05671bbc75/datasets/coco.py#L103

**Comment by zzzxxxttt** [comment]
This is because the axis origin of an image is at the top-left corner, just like a numpy array
